const char *helpStr =
"Usage: tek4010 [options] COMMAND [...]\n"
"\n"
"    -h, --help      Print this help and exit.\n"
"\n"
"    -noexit         do not close window after completion of \"command\"\n"
"\n"
"    -raw            do not execute an automatic CR (carriage return) after a\n"
"                    LF (line feed)\n"
"\n"
"    -tab1           execute a blank instead of a tab to the next 8-character column\n"
"\n"
"    -b100000, -b38400, -b19200, -b9600, -b4800, -b2400, -b1200, -b600, -b300\n"
"                    Emulate a baud rate. Without one of these arguments,\n"
"                    the baud rate is 19200 baud. The original Tektronix\n"
"                    4010 had a maximal baud rate of 9600 baud. The\n"
"                    4014 could support up to 100000 baud with a special\n"
"                    interface. With the small baud rates you can emulate\n"
"                    1970s style modem performance. Early modems had a\n"
"                    baud rate of 300.\n"
"\n"
"    -full           in this mode the tek4010 emulator creates a full screen window and\n"
"                    uses the full resolution of the 4014 with the enhanced\n"
"                    graphics module installed, scaled down to the actual\n"
"                    window size. Use ctrl-q to close the tek4010 window.\n"
"\n"
"    -fullv          in this mode the tek4010 emulator creates a decorated window\n"
"                    using the maximal vertical space available. The full\n"
"                    resolution of the 4014 with the enhanced graphics\n"
"                    module installed is used, scaled down to the actual\n"
"                    window size\n"
"\n"
"    -ARDS           display ARDS data\n"
"\n"
"    -APL            emulate Tektronix 4013/4015 with alternative APL character set.\n"
"                    Details see below.\n"
"\n"
"    -autoClear      erase screen if a line feed is executed at the bottom of the screen.\n"
"                    This makes it sometimes easier to use tek4010 as\n"
"                    the only terminal. It is not the behaviour of the\n"
"                    original hardware.\n"
"\n"
"    -keepsize       tek4010 sets the fontsize to normal whenever the screen is erased.\n"
"                    This option keeps the currently selected font size\n"
"                    until it is changed with a new escape sequence. Some\n"
"                    historic plot files will not reset the font size\n"
"                    back to normal if this option is set.\n"
"\n"
"    -hidecursor     hides the cursor. Do not set while using GIN mode.\n"
"\n"
"    -wait n         Close window n seconds after completion of \"command\".\n"
"                    It does not make sense to use -noexit together with -wait.\n"
"\n"
"    -fast           Use fast rendering without fading. Recommended on slower systems.\n"
"                    This mode can be used to avoid a slow and choppy display.\n"
"                    -fast is automatically used for baud rates above 19200.\n"
;
